package cn.victorplus.vehicle.bean.db;


import cn.victorplus.vehicle.bean.BaseEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class CarBrand extends BaseEntity {
  /**
  品牌ID
  **/
  private Integer bId;
  /**
  品牌名称
  **/
  private String bName;
  /**
  首字母
  **/
  private String bFirstletter;
  /**
  添加时间
  **/
  private Date bCreatetime;
  /**
  最后修改时间
  **/
  private Date bModifytime;
  private Long cuid;
  private String cuname;

  public CarBrand() {
  }

  public CarBrand(
          Integer bId,
          String bName,
          String bFirstletter,
          String bQuote,
          Date bCreatetime,
          Date bModifytime) {
    this.bId = bId;
    this.bName = bName;
    this.bFirstletter = bFirstletter;
    this.bCreatetime = bCreatetime;
    this.bModifytime = bModifytime;
  }

  public CarBrand(Integer bId, String bName, String bFirstletter, Date bCreatetime, Date bModifytime, Long cuid, String cuname) {
    this.bId = bId;
    this.bName = bName;
    this.bFirstletter = bFirstletter;
    this.bCreatetime = bCreatetime;
    this.bModifytime = bModifytime;
    this.cuid = cuid;
    this.cuname = cuname;
  }

  public Integer getBId() {
  	return bId;
  }
	
  public void setBId(Integer bId) {
    this.bId = bId;
  }
	
  public String getBName() {
  	return bName;
  }
	
  public void setBName(String bName) {
    this.bName = bName;
  }
	
  public String getBFirstletter() {
  	return bFirstletter;
  }
	
  public void setBFirstletter(String bFirstletter) {
    this.bFirstletter = bFirstletter;
  }
	
  public Date getBCreatetime() {
  	return bCreatetime;
  }
	
  public void setBCreatetime(Date bCreatetime) {
    this.bCreatetime = bCreatetime;
  }
	
  public Date getBModifytime() {
  	return bModifytime;
  }
	
  public void setBModifytime(Date bModifytime) {
    this.bModifytime = bModifytime;
  }

  public Integer getbId() {
    return bId;
  }

  public void setbId(Integer bId) {
    this.bId = bId;
  }

  public String getbName() {
    return bName;
  }

  public void setbName(String bName) {
    this.bName = bName;
  }

  public String getbFirstletter() {
    return bFirstletter;
  }

  public void setbFirstletter(String bFirstletter) {
    this.bFirstletter = bFirstletter;
  }

  public Date getbCreatetime() {
    return bCreatetime;
  }

  public void setbCreatetime(Date bCreatetime) {
    this.bCreatetime = bCreatetime;
  }

  public Date getbModifytime() {
    return bModifytime;
  }

  public void setbModifytime(Date bModifytime) {
    this.bModifytime = bModifytime;
  }

  public Long getCuid() {
    return cuid;
  }

  public void setCuid(Long cuid) {
    this.cuid = cuid;
  }

  public String getCuname() {
    return cuname;
  }

  public void setCuname(String cuname) {
    this.cuname = cuname;
  }
}
