package cn.victorplus.vehicle.bean.db;


import cn.victorplus.vehicle.bean.BaseEntity;

import java.util.Date;

/**
 * WARNING:
 * this code is generated by CodeMonkey
 * please DO NOT modify this file
 **/
public class CarModels extends BaseEntity {
    /**
     * 车型id
     **/
    private Long mId;
    /**
     * 车型名称
     **/
    private String mName;
    /**
     * 品牌ID
     **/
    private Long bId;
    /**
     * 厂家ID
     **/
    private Long fId;
    /**
     * 车系ID
     **/
    private Long sId;
    /**
     * 年代款ID
     **/
    private Long yId;
    /**
     * 数据来源
     **/
    private String sQuote;
    /**
     * 厂商指导价
     **/
    private Integer mMsrp;
    /**
     * 市场最高价
     **/
    private Integer mMaxprice;
    /**
     * 市场最低价
     **/
    private Integer mMinprice;
    /**
     * 吨位
     **/
    private String mTonnage;
    /**
     * 档位
     **/
    private String mGear;
    /**
     * 驱动方式
     **/
    private String mDrivingmode;
    /**
     * 变速箱
     **/
    private String mGearbox;
    /**
     * 燃料类型
     **/
    private String mFuel;
    /**
     * 燃料类型
     **/
    private String mliter;
    /**
     * 座位数
     **/
    private String mSeats;
    /**
     * 级别
     **/
    private String mLevel;
    /**
     * 状态
     **/
    private Integer mState;
    /**
     * 创建时间
     **/
    private Date mCreatetime;
    /**
     * 最后修改时间
     **/
    private Date mModifytime;
    private Long cuid;
    private String cuname;

    public CarModels() {
    }

    public CarModels(
            Long mId,
            String mName,
            Long bId,
            Long fId,
            Long sId,
            Long yId,
            String sQuote,
            Integer mMsrp,
            Integer mMaxprice,
            Integer mMinprice,
            String mTonnage,
            String mGear,
            String mDrivingmode,
            String mGearbox,
            String mFuel,
            String mliter,
            String mSeats,
            String mLevel,
            Integer mState,
            Date mCreatetime,
            Date mModifytime) {
        this.mId = mId;
        this.mName = mName;
        this.bId = bId;
        this.fId = fId;
        this.sId = sId;
        this.yId = yId;
        this.sQuote = sQuote;
        this.mMsrp = mMsrp;
        this.mMaxprice = mMaxprice;
        this.mMinprice = mMinprice;
        this.mTonnage = mTonnage;
        this.mGear = mGear;
        this.mDrivingmode = mDrivingmode;
        this.mGearbox = mGearbox;
        this.mFuel = mFuel;
        this.mFuel = mliter;
        this.mSeats = mSeats;
        this.mLevel = mLevel;
        this.mState = mState;
        this.mCreatetime = mCreatetime;
        this.mModifytime = mModifytime;
    }

    public CarModels(Long mId, String mName, Long bId, Long fId, Long sId, Long yId, String sQuote, Integer mMsrp, Integer mMaxprice, Integer mMinprice, String mTonnage, String mGear, String mDrivingmode, String mGearbox, String mFuel, String mliter, String mSeats, String mLevel, Integer mState, Date mCreatetime, Date mModifytime, Long cuid, String cuname) {
        this.mId = mId;
        this.mName = mName;
        this.bId = bId;
        this.fId = fId;
        this.sId = sId;
        this.yId = yId;
        this.sQuote = sQuote;
        this.mMsrp = mMsrp;
        this.mMaxprice = mMaxprice;
        this.mMinprice = mMinprice;
        this.mTonnage = mTonnage;
        this.mGear = mGear;
        this.mDrivingmode = mDrivingmode;
        this.mGearbox = mGearbox;
        this.mFuel = mFuel;
        this.mliter = mliter;
        this.mSeats = mSeats;
        this.mLevel = mLevel;
        this.mState = mState;
        this.mCreatetime = mCreatetime;
        this.mModifytime = mModifytime;
        this.cuid = cuid;
        this.cuname = cuname;
    }

    public Long getMId() {
        return mId;
    }

    public void setMId(Long mId) {
        this.mId = mId;
    }

    public String getMName() {
        return mName;
    }

    public void setMName(String mName) {
        this.mName = mName;
    }

    public Long getBId() {
        return bId;
    }

    public void setBId(Long bId) {
        this.bId = bId;
    }

    public Long getFId() {
        return fId;
    }

    public void setFId(Long fId) {
        this.fId = fId;
    }

    public Long getSId() {
        return sId;
    }

    public void setSId(Long sId) {
        this.sId = sId;
    }

    public Long getYId() {
        return yId;
    }

    public void setYId(Long yId) {
        this.yId = yId;
    }

    public String getSQuote() {
        return sQuote;
    }

    public void setSQuote(String sQuote) {
        this.sQuote = sQuote;
    }

    public Integer getMMsrp() {
        return mMsrp;
    }

    public void setMMsrp(Integer mMsrp) {
        this.mMsrp = mMsrp;
    }

    public Integer getMMaxprice() {
        return mMaxprice;
    }

    public void setMMaxprice(Integer mMaxprice) {
        this.mMaxprice = mMaxprice;
    }

    public Integer getMMinprice() {
        return mMinprice;
    }

    public void setMMinprice(Integer mMinprice) {
        this.mMinprice = mMinprice;
    }

    public String getMTonnage() {
        return mTonnage;
    }

    public void setMTonnage(String mTonnage) {
        this.mTonnage = mTonnage;
    }

    public String getMGear() {
        return mGear;
    }

    public void setMGear(String mGear) {
        this.mGear = mGear;
    }

    public String getMDrivingmode() {
        return mDrivingmode;
    }

    public void setMDrivingmode(String mDrivingmode) {
        this.mDrivingmode = mDrivingmode;
    }

    public String getMGearbox() {
        return mGearbox;
    }

    public void setMGearbox(String mGearbox) {
        this.mGearbox = mGearbox;
    }

    public String getMFuel() {
        return mFuel;
    }

    public void setMFuel(String mFuel) {
        this.mFuel = mFuel;
    }

    public String getMSeats() {
        return mSeats;
    }

    public void setMSeats(String mSeats) {
        this.mSeats = mSeats;
    }

    public String getMLevel() {
        return mLevel;
    }

    public void setMLevel(String mLevel) {
        this.mLevel = mLevel;
    }

    public Integer getMState() {
        return mState;
    }

    public void setMState(Integer mState) {
        this.mState = mState;
    }

    public Date getMCreatetime() {
        return mCreatetime;
    }

    public void setMCreatetime(Date mCreatetime) {
        this.mCreatetime = mCreatetime;
    }

    public Date getMModifytime() {
        return mModifytime;
    }

    public void setMModifytime(Date mModifytime) {
        this.mModifytime = mModifytime;
    }

    public Long getmId() {
        return mId;
    }

    public void setmId(Long mId) {
        this.mId = mId;
    }

    public String getmName() {
        return mName;
    }

    public void setmName(String mName) {
        this.mName = mName;
    }

    public Long getbId() {
        return bId;
    }

    public void setbId(Long bId) {
        this.bId = bId;
    }

    public Long getfId() {
        return fId;
    }

    public void setfId(Long fId) {
        this.fId = fId;
    }

    public Long getsId() {
        return sId;
    }

    public void setsId(Long sId) {
        this.sId = sId;
    }

    public Long getyId() {
        return yId;
    }

    public void setyId(Long yId) {
        this.yId = yId;
    }

    public String getsQuote() {
        return sQuote;
    }

    public void setsQuote(String sQuote) {
        this.sQuote = sQuote;
    }

    public Integer getmMsrp() {
        return mMsrp;
    }

    public void setmMsrp(Integer mMsrp) {
        this.mMsrp = mMsrp;
    }

    public Integer getmMaxprice() {
        return mMaxprice;
    }

    public void setmMaxprice(Integer mMaxprice) {
        this.mMaxprice = mMaxprice;
    }

    public Integer getmMinprice() {
        return mMinprice;
    }

    public void setmMinprice(Integer mMinprice) {
        this.mMinprice = mMinprice;
    }

    public String getmTonnage() {
        return mTonnage;
    }

    public void setmTonnage(String mTonnage) {
        this.mTonnage = mTonnage;
    }

    public String getmGear() {
        return mGear;
    }

    public void setmGear(String mGear) {
        this.mGear = mGear;
    }

    public String getmDrivingmode() {
        return mDrivingmode;
    }

    public void setmDrivingmode(String mDrivingmode) {
        this.mDrivingmode = mDrivingmode;
    }

    public String getmGearbox() {
        return mGearbox;
    }

    public void setmGearbox(String mGearbox) {
        this.mGearbox = mGearbox;
    }

    public String getmFuel() {
        return mFuel;
    }

    public void setmFuel(String mFuel) {
        this.mFuel = mFuel;
    }

    public String getmSeats() {
        return mSeats;
    }

    public void setmSeats(String mSeats) {
        this.mSeats = mSeats;
    }

    public String getmLevel() {
        return mLevel;
    }

    public void setmLevel(String mLevel) {
        this.mLevel = mLevel;
    }

    public Integer getmState() {
        return mState;
    }

    public void setmState(Integer mState) {
        this.mState = mState;
    }

    public Date getmCreatetime() {
        return mCreatetime;
    }

    public void setmCreatetime(Date mCreatetime) {
        this.mCreatetime = mCreatetime;
    }

    public Date getmModifytime() {
        return mModifytime;
    }

    public void setmModifytime(Date mModifytime) {
        this.mModifytime = mModifytime;
    }

    public Long getCuid() {
        return cuid;
    }

    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    public String getCuname() {
        return cuname;
    }

    public void setCuname(String cuname) {
        this.cuname = cuname;
    }

    public String getMliter() {
        return mliter;
    }

    public void setMliter(String mliter) {
        this.mliter = mliter;
    }
}

