package cn.victorplus.vehicle.bean.db;


import cn.victorplus.vehicle.bean.BaseEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class CarSeries extends BaseEntity {
  /**
  车系ID
  **/
  private Integer sId;
  /**
  车系名称
  **/
  private String sName;
  /**
  品牌ID
  **/
  private Integer bId;
  /**
  厂家ID
  **/
  private Integer fId;
  /**
  创建时间
  **/
  private Date sCreatetime;
  /**
  最后修改时间
  **/
  private Date sModifytime;
  private Long cuid;
  private String cuname;

  public CarSeries() {
  }

  public CarSeries(
          Integer sId,
          String sName,
          String sQuote,
          Integer bId,
          Integer fId,
          Date sCreatetime,
          Date sModifytime) {
    this.sId = sId;
    this.sName = sName;
    this.bId = bId;
    this.fId = fId;
    this.sCreatetime = sCreatetime;
    this.sModifytime = sModifytime;
  }

  public CarSeries(Integer sId, String sName, Integer bId, Integer fId, Date sCreatetime, Date sModifytime, Long cuid, String cuname) {
    this.sId = sId;
    this.sName = sName;
    this.bId = bId;
    this.fId = fId;
    this.sCreatetime = sCreatetime;
    this.sModifytime = sModifytime;
    this.cuid = cuid;
    this.cuname = cuname;
  }

  public Integer getSId() {
  	return sId;
  }
	
  public void setSId(Integer sId) {
    this.sId = sId;
  }
	
  public String getSName() {
  	return sName;
  }
	
  public void setSName(String sName) {
    this.sName = sName;
  }
	
  public Integer getBId() {
  	return bId;
  }
	
  public void setBId(Integer bId) {
    this.bId = bId;
  }
	
  public Integer getFId() {
  	return fId;
  }
	
  public void setFId(Integer fId) {
    this.fId = fId;
  }
	
  public Date getSCreatetime() {
  	return sCreatetime;
  }
	
  public void setSCreatetime(Date sCreatetime) {
    this.sCreatetime = sCreatetime;
  }
	
  public Date getSModifytime() {
  	return sModifytime;
  }
	
  public void setSModifytime(Date sModifytime) {
    this.sModifytime = sModifytime;
  }

  public Integer getsId() {
    return sId;
  }

  public void setsId(Integer sId) {
    this.sId = sId;
  }

  public String getsName() {
    return sName;
  }

  public void setsName(String sName) {
    this.sName = sName;
  }

  public Integer getbId() {
    return bId;
  }

  public void setbId(Integer bId) {
    this.bId = bId;
  }

  public Integer getfId() {
    return fId;
  }

  public void setfId(Integer fId) {
    this.fId = fId;
  }

  public Date getsCreatetime() {
    return sCreatetime;
  }

  public void setsCreatetime(Date sCreatetime) {
    this.sCreatetime = sCreatetime;
  }

  public Date getsModifytime() {
    return sModifytime;
  }

  public void setsModifytime(Date sModifytime) {
    this.sModifytime = sModifytime;
  }

  public Long getCuid() {
    return cuid;
  }

  public void setCuid(Long cuid) {
    this.cuid = cuid;
  }

  public String getCuname() {
    return cuname;
  }

  public void setCuname(String cuname) {
    this.cuname = cuname;
  }

}
