package cn.victorplus.vehicle.bean.db;


import cn.victorplus.vehicle.bean.BaseEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class Che300Brand extends BaseEntity {
  /**
  品牌ID
  **/
  private Long brandId;
  /**
  品牌名称
  **/
  private String brandName;
  /**
  首字母
  **/
  private String brandFirstLetter;
  /**
  添加时间
  **/
  private Date brandCreatetime;
  /**
  最后修改时间
  **/
  private Date brandModifytime;

  public Che300Brand() {
  }

  public Che300Brand(Long brandId, String brandName, String brandFirstLetter, Date brandCreatetime, Date brandModifytime) {
    this.brandId = brandId;
    this.brandName = brandName;
    this.brandFirstLetter = brandFirstLetter;
    this.brandCreatetime = brandCreatetime;
    this.brandModifytime = brandModifytime;
  }

  public Long getBrandId() {
    return brandId;
  }

  public void setBrandId(Long brandId) {
    this.brandId = brandId;
  }

  public String getBrandName() {
    return brandName;
  }

  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }

  public String getBrandFirstLetter() {
    return brandFirstLetter;
  }

  public void setBrandFirstLetter(String brandFirstLetter) {
    this.brandFirstLetter = brandFirstLetter;
  }

  public Date getBrandCreatetime() {
    return brandCreatetime;
  }

  public void setBrandCreatetime(Date brandCreatetime) {
    this.brandCreatetime = brandCreatetime;
  }

  public Date getBrandModifytime() {
    return brandModifytime;
  }

  public void setBrandModifytime(Date brandModifytime) {
    this.brandModifytime = brandModifytime;
  }

  @Override
  public String toString() {
    return "Che300Brand{" +
            "brandId=" + brandId +
            ", brandName='" + brandName + '\'' +
            ", brandFirstLetter='" + brandFirstLetter + '\'' +
            ", brandCreatetime=" + brandCreatetime +
            ", brandModifytime=" + brandModifytime +
            '}';
  }
}
