package cn.victorplus.vehicle.bean.db;


import cn.victorplus.vehicle.bean.BaseEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class Che300Series extends BaseEntity {
  /**
  车系ID
  **/
  private Long seriesId;
  /**
  车系名称
  **/
  private String seriesName;
  /**
  车系组名
  **/
  private String seriesGroupName;
  /**
  品牌ID
  **/
  private Long brandId;
  /**
  创建时间
  **/
  private Date seriesCreatetime;
  /**
  最后修改时间
  **/
  private Date seriesModifytime;

  public Che300Series() {
  }

  public Che300Series(Long seriesId, String seriesName, String seriesGroupName, Long brandId, Date seriesCreatetime, Date seriesModifytime) {
    this.seriesId = seriesId;
    this.seriesName = seriesName;
    this.seriesGroupName = seriesGroupName;
    this.brandId = brandId;
    this.seriesCreatetime = seriesCreatetime;
    this.seriesModifytime = seriesModifytime;
  }

  public Long getSeriesId() {
    return seriesId;
  }

  public void setSeriesId(Long seriesId) {
    this.seriesId = seriesId;
  }

  public String getSeriesName() {
    return seriesName;
  }

  public void setSeriesName(String seriesName) {
    this.seriesName = seriesName;
  }

  public String getSeriesGroupName() {
    return seriesGroupName;
  }

  public void setSeriesGroupName(String seriesGroupName) {
    this.seriesGroupName = seriesGroupName;
  }

  public Long getBrandId() {
    return brandId;
  }

  public void setBrandId(Long brandId) {
    this.brandId = brandId;
  }

  public Date getSeriesCreatetime() {
    return seriesCreatetime;
  }

  public void setSeriesCreatetime(Date seriesCreatetime) {
    this.seriesCreatetime = seriesCreatetime;
  }

  public Date getSeriesModifytime() {
    return seriesModifytime;
  }

  public void setSeriesModifytime(Date seriesModifytime) {
    this.seriesModifytime = seriesModifytime;
  }

  @Override
  public String toString() {
    return "Che300Series{" +
            "seriesId=" + seriesId +
            ", seriesName='" + seriesName + '\'' +
            ", seriesGroupName='" + seriesGroupName + '\'' +
            ", brandId=" + brandId +
            ", seriesCreatetime=" + seriesCreatetime +
            ", seriesModifytime=" + seriesModifytime +
            '}';
  }
}
