package cn.victorplus.vehicle.bean.db;


import cn.victorplus.vehicle.bean.BaseEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class Che300Year extends BaseEntity {
  /**
  年代款ID
  **/
  private Long yearId;
  /**
  年代款名称
  **/
  private String yearName;
  /**
  车系ID
  **/
  private Long seriesId;
  /**
  创建时间
  **/
  private Date yearCreatetime;
  /**
  最后修改时间
  **/
  private Date yearModifytime;

  public Che300Year() {
  }

  public Che300Year(Long yearId, String yearName, Long seriesId, Date yearCreatetime, Date yearModifytime) {
    this.yearId = yearId;
    this.yearName = yearName;
    this.seriesId = seriesId;
    this.yearCreatetime = yearCreatetime;
    this.yearModifytime = yearModifytime;
  }

  public Long getYearId() {
    return yearId;
  }

  public void setYearId(Long yearId) {
    this.yearId = yearId;
  }

  public String getYearName() {
    return yearName;
  }

  public void setYearName(String yearName) {
    this.yearName = yearName;
  }

  public Long getSeriesId() {
    return seriesId;
  }

  public void setSeriesId(Long seriesId) {
    this.seriesId = seriesId;
  }

  public Date getYearCreatetime() {
    return yearCreatetime;
  }

  public void setYearCreatetime(Date yearCreatetime) {
    this.yearCreatetime = yearCreatetime;
  }

  public Date getYearModifytime() {
    return yearModifytime;
  }

  public void setYearModifytime(Date yearModifytime) {
    this.yearModifytime = yearModifytime;
  }

  @Override
  public String toString() {
    return "Che300Year{" +
            "yearId=" + yearId +
            ", yearName='" + yearName + '\'' +
            ", seriesId=" + seriesId +
            ", yearCreatetime=" + yearCreatetime +
            ", yearModifytime=" + yearModifytime +
            '}';
  }
}
