package cn.victorplus.vehicle.bean.db;

import java.math.BigDecimal;

/**
 * 进项发票主表
 * WARNING:
 * this code is generated by code-generator
 * please DO NOT modify this file
 *  code-generator
 *  2020-05-25 11:24:44
 */
public class TPurchaserInvoice {
  /**
   * 发票序列号主键
   */
  private String invoiceId;
  /**
   * 预制发票序列号
   */
  private String preInvoiceId;
  /**
   * 结算单序号
   */
  private String settlementId;
  /**
   * 结算单号
   */
  private String settlementNo;
  /**
   * 原结算单号
   */
  private String originSettlementNo;
  /**
   * 销方发票主表ID
   */
  private String sellerInvoiceId;
  /**
   * 国税发票主表ID
   */
  private Integer taxInvoiceId;
  /**
   * 扫描发票主表ID
   */
  private Integer scanInvoiceId;
  /**
   * 销方信息状态0-未购买服务1-购买服务数据未到2-数据已到
   */
  private String sellerInfoStatus;
  /**
   * 国税信息状态0-未购买服务1-购买服务数据未到2-数据已到
   */
  private String taxInfoStatus;
  /**
   * 扫描信息状态0-未购买服务1-购买服务数据未到2-数据已到
   */
  private String scanInfoStatus;
  /**
   * 发票类型c-增值税普通发票  s-增值税专用发票 j-机动车销售统一发票 ce-增值税电子普通发票 cr-增值税普通发票（卷票）t-通用机打发票 （暂不显示）
   */
  private String invoiceType;
  /**
   * 发票代码
   */
  private String invoiceCode;
  /**
   * 发票号码
   */
  private String invoiceNo;
  /**
   * 销方租户代码
   */
  private String sellerTenantCode;
  /**
   * 销方租户公司编号
   */
  private String sellerNo;
  /**
   * 购方租户定义的销方公司编号
   */
  private String sellerNoFromPurchaser;
  /**
   * 销方公司代码
   */
  private String sellerCode;
  /**
   * 销方纳税人识别号
   */
  private String sellerTaxNo;
  /**
   * 销方名称
   */
  private String sellerName;
  /**
   * 销方地址电话
   */
  private String sellerAddrTel;
  /**
   * 销方地址
   */
  private String sellerAddress;
  /**
   * 销方电话
   */
  private String sellerTel;
  /**
   * 销方银行名称账号
   */
  private String sellerBankInfo;
  /**
   * 销方银行名称
   */
  private String sellerBankName;
  /**
   * 销方银行账号
   */
  private String sellerBankAccount;
  /**
   * 购方租户代码
   */
  private String purchaserTenantCode;
  /**
   * 购方租户公司编号
   */
  private String purchaserNo;
  /**
   * 销方租户定义的购方公司编号
   */
  private String purchaserNoFromSeller;
  /**
   * 购方公司代码
   */
  private String purchaserCode;
  /**
   * 购方纳税人识别号
   */
  private String purchaserTaxNo;
  /**
   * 国税对应的购方公司名称
   */
  private String taxPurchaserName;
  /**
   * 购方名称
   */
  private String purchaserName;
  /**
   * 购方地址电话
   */
  private String purchaserAddrTel;
  /**
   * 购方地址
   */
  private String purchaserAddress;
  /**
   * 购方电话
   */
  private String purchaserTel;
  /**
   * 购方银行名称账号
   */
  private String purchaserBankInfo;
  /**
   * 购方银行名称
   */
  private String purchaserBankName;
  /**
   * 购方银行账号
   */
  private String purchaserBankAccount;
  /**
   * 税率
   */
  private BigDecimal taxRate;
  /**
   * 不含税金额
   */
  private BigDecimal amountWithoutTax;
  /**
   * 税额
   */
  private BigDecimal taxAmount;
  /**
   * 含税金额
   */
  private BigDecimal amountWithTax;
  /**
   * 发票开票日期
   */
  private String paperDrewDate;
  /**
   * 发票来源
   */
  private String invoiceOrig;
  /**
   * 二维码发票标记0-非二维码发票 1-二维码发票
   */
  private String twoCodeFlag;
  /**
   * 二维密文
   */
  private String cipherTextTwoCode;
  /**
   * 密文
   */
  private String cipherText;
  /**
   * 备注
   */
  private String REMARK;
  /**
   * 收款人姓名
   */
  private String cashierName;
  /**
   * 复核人姓名
   */
  private String checkerName;
  /**
   * 开票人姓名
   */
  private String invoicerName;
  /**
   * 机器编码
   */
  private String machineCode;
  /**
   * 扫描时间
   */
  private String scanTime;
  /**
   * 扫描顺序
   */
  private Integer scanOrder;
  /**
   * 扫描操作账号
   */
  private String scanUserId;
  /**
   * 扫描账号对应用户名
   */
  private String scanUserName;
  /**
   * 扫描批次号
   */
  private String scanBatchNo;
  /**
   * 抵扣联影像路径
   */
  private String scanDeductionImageUrl;
  /**
   * 发票联影像路径
   */
  private String scanInvoiceImageUrl;
  /**
   * 扫描状态 1-已扫描 0-未扫描
   */
  private String scanStatus;
  /**
   * 扫描次数
   */
  private Integer scanNum;
  /**
   * 抽取时间
   */
  private String drawoutTime;
  /**
   * 抽取操作账号
   */
  private String drawoutUserId;
  /**
   * 是否需要认证1-需要2-不需要
   */
  private String isNeedAuth;
  /**
   * 封锁标记  A-认证封锁 B-手工封锁
   */
  private String lockFlag;
  /**
   * 发票状态1-正常0-作废6-失控
   */
  private String STATUS;
  /**
   * 原发票号码
   */
  private String originInvoiceNo;
  /**
   * 原发票代码
   */
  private String originInvoiceCode;
  /**
   * 红字信息表编号
   */
  private String redNotificationNo;
  /**
   * 红冲时间
   */
  private String redTime;
  /**
   * 红冲状态1-待红冲 3-待部分红冲 2-红冲 4-部分红冲
   */
  private String redFlag;
  /**
   * 处理标记
   */
  private String processFlag;
  /**
   * 处理备注
   */
  private String processRemark;
  /**
   * 系统来源
   */
  private String systemOrig;
  /**
   * 校验码
   */
  private String checkCode;
  /**
   * 业务批次号
   */
  private String tpBatchNo;
  /**
   * 业务状态
   */
  private String TP;
  /**
   * 审核状态0-待审核1-审核中2-不具备审核条件3-已审核
   */
  private String auditStatus;
  /**
   * 底账获取状态1-已获取0-未获取
   */
  private String elGetInfoFlag;
  /**
   * 电子底帐状态 0-未勾选 1-已勾选 2-底账确认中 3-底账确认失败 4-已确认
   */
  private String elFlag;
  /**
   * 电子底帐时间
   */
  private String elTime;
  /**
   * 底账账号
   */
  private String elUserId;
  /**
   * 电子底帐请求操作时间
   */
  private String elRequestTime;
  /**
   * 电子底帐请求操作账号
   */
  private String elRequestUserId;
  /**
   * 勾选时间
   */
  private String elCheckTime;
  /**
   * 所属期
   */
  private String elTaxPeriod;
  /**
   * 确认请求时间
   */
  private String elEnsureRequestTime;
  /**
   * ?确认请求操作账号
   */
  private String elEnsureRequestUserId;
  /**
   * 确认时间
   */
  private String elEnsureTime;
  /**
   * 底账确认备注
   */
  private String elEnsureRemark;
  /**
   * 协同类型0-非协同1-协同空-以票易通平台配置决定
   */
  private String cooperateFlag;
  /**
   * 退回状态1-退回  2-撤消退回
   */
  private String retreatStatus;
  /**
   * 退回备注
   */
  private String retreatRemark;
  /**
   * 销方查看影像标志1-允许销方查看影像
   */
  private String sellerViewImageFlag;
  /**
   * 异常标志0-正常1-异常
   */
  private String exceptionFlag;
  /**
   * 多来源发票信息比对标记：1-比对不一致
   */
  private String comparisonFlag;
  /**
   * 认证结果 0-认证中 1-认证成功 2-认证失败
   */
  private String authResult;
  /**
   * 认证时间
   */
  private String authTime;
  /**
   * 认证说明
   */
  private String authRemark;
  /**
   * 认证发送时间
   */
  private String authRequestTime;
  /**
   * 认证操作员
   */
  private String authRequestUserId;
  /**
   * 认证操作人姓名
   */
  private String authRequestUserName;
  /**
   * 认证途径A-通过票易通传统认证B-通过票易通底账确认C1-通过体外导入的非票易通传统认证C2-通过票易通导入的非票易通底账确认D1-通过票易通获取的非票易通传统认证D2-通过票易通底账获取的非票易通底账确认
   */
  private String authRoute;
  /**
   * 认证状态0-未认证1-认证成功2-传统认证中3-底账认证中4-认证失败5-认证异常6-退税认证中7-已抵扣勾选8-非抵扣勾选9-抵扣勾选中10-抵扣取消勾选中
   */
  private String authStatus;
  /**
   * 验证状态 0-未购买验真 1-待验真 2-验真中 3-国税暂无此票 4-验真成功
   */
  private String taxFlag;
  /**
   * 验真时间
   */
  private String taxRequestTime;
  /**
   * 服务代码0000000001-购买验真服务
   */
  private String serviceCode;
  /**
   *      1-是
   */
  private String isNeedAllInfo;
  /**
   * PDF路径
   */
  private String pdfPath;
  /**
   * 运维状态1-运维状态
   */
  private String opStatus;
  /**
   * 平台预制发票正式信息回填时间
   */
  private String createTime;
  /**
   * 平台预制发票正式信息回填操作账号
   */
  private String createUserId;
  /**
   * 修改时间
   */
  private String updateTime;
  /**
   * 修改人
   */
  private String updateUserId;
  /**
   * 结算单匹配状态1-已匹配2-未匹配3-有冲突
   */
  private String settlementMatchStatus;
  /**
   * 物流状态
   */
  private String logisticsStatus;
  /**
   * 打印内容标志 0-打印单价和数量 1-不打印单价和数量,默认0
   */
  private String printContentFlag;
  /**
   * 差异状态
   */
  private String diffStatus;
  /**
   * 税局代开标志Y,是；N，否
   */
  private String taxBureauOpenType;
  /**
   * 消除过异常预警标记 0-未消除过 1-消除过
   */
  private String cancelExcepitonFlag;
  /**
   * 认证异常原因
   */
  private String authExceptionReason;
  /**
   * 销货清单 0-没有1-有 (默认空-未知)
   */
  private String saleListFileFlag;
  /**
   * 明细来源 1-销方 2- 国税 3-扫描
   */
  private String invoiceItemOrig;
  /**
   * 验真备注
   */
  private String taxFlagRemark;
  /**
   * 发票标记:ct(0-普通通行费，1-特殊通行费)
   */
  private String invoiceTag;
  /**
   * 贸易类型 1-进口 2-出口
   */
  private String invoiceTradeType;
  /**
   * 入库单匹配状态 1-匹配 2-待匹配
   */
  private String inboundorderMatchStatus;
  /**
   * 与入库单匹配数量
   */
  private BigDecimal inboundorderMatchNum;
  /**
   * 第一次匹配
   */
  private String matchFirst;
  /**
   * 第二次匹配
   */
  private String matchSecond;
  /**
   * tp凭证号
   */
  private String tpCertificateNo;
  /**
   * 凭证所属期
   */
  private String tpCertificatePeriod;
  /**
   * 自定义字段1
   */
  private String customizeRemark1;
  /**
   * 自定义字段2
   */
  private String customizeRemark2;
  /**
   * 自定义字段3
   */
  private String customizeRemark3;
  /**
   * 拓展字段1
   */
  private String EXT1;
  /**
   * 拓展字段2
   */
  private String EXT2;
  /**
   * 拓展字段3
   */
  private String EXT3;
  /**
   * 拓展字段4
   */
  private String EXT4;
  /**
   * 拓展字段5
   */
  private String EXT5;
  /**
   * 拓展字段6
   */
  private String EXT6;
  /**
   * 拓展字段7
   */
  private String EXT7;
  /**
   * 拓展字段8
   */
  private String EXT8;
  /**
   * 拓展字段9
   */
  private String EXT9;
  /**
   * 拓展字段10
   */
  private String EXT10;
  /**
   * 税编简称状态 0--合规 1--不合规
   */
  private String shortTaxcodeStatus;
  /**
   * 有效税额
   */
  private BigDecimal effectiveTaxAmount;
  /**
   * 发票用途 1-可抵扣  2-不抵扣
   */
  private String useRoute;

  public String getInvoiceId() {
  	return invoiceId;
  }
	
  public void setInvoiceId(String invoiceId) {
    this.invoiceId = invoiceId;
  }
	
  public String getPreInvoiceId() {
  	return preInvoiceId;
  }
	
  public void setPreInvoiceId(String preInvoiceId) {
    this.preInvoiceId = preInvoiceId;
  }
	
  public String getSettlementId() {
  	return settlementId;
  }
	
  public void setSettlementId(String settlementId) {
    this.settlementId = settlementId;
  }
	
  public String getSettlementNo() {
  	return settlementNo;
  }
	
  public void setSettlementNo(String settlementNo) {
    this.settlementNo = settlementNo;
  }
	
  public String getOriginSettlementNo() {
  	return originSettlementNo;
  }
	
  public void setOriginSettlementNo(String originSettlementNo) {
    this.originSettlementNo = originSettlementNo;
  }
	
  public String getSellerInvoiceId() {
  	return sellerInvoiceId;
  }
	
  public void setSellerInvoiceId(String sellerInvoiceId) {
    this.sellerInvoiceId = sellerInvoiceId;
  }
	
  public Integer getTaxInvoiceId() {
  	return taxInvoiceId;
  }
	
  public void setTaxInvoiceId(Integer taxInvoiceId) {
    this.taxInvoiceId = taxInvoiceId;
  }
	
  public Integer getScanInvoiceId() {
  	return scanInvoiceId;
  }
	
  public void setScanInvoiceId(Integer scanInvoiceId) {
    this.scanInvoiceId = scanInvoiceId;
  }
	
  public String getSellerInfoStatus() {
  	return sellerInfoStatus;
  }
	
  public void setSellerInfoStatus(String sellerInfoStatus) {
    this.sellerInfoStatus = sellerInfoStatus;
  }
	
  public String getTaxInfoStatus() {
  	return taxInfoStatus;
  }
	
  public void setTaxInfoStatus(String taxInfoStatus) {
    this.taxInfoStatus = taxInfoStatus;
  }
	
  public String getScanInfoStatus() {
  	return scanInfoStatus;
  }
	
  public void setScanInfoStatus(String scanInfoStatus) {
    this.scanInfoStatus = scanInfoStatus;
  }
	
  public String getInvoiceType() {
  	return invoiceType;
  }
	
  public void setInvoiceType(String invoiceType) {
    this.invoiceType = invoiceType;
  }
	
  public String getInvoiceCode() {
  	return invoiceCode;
  }
	
  public void setInvoiceCode(String invoiceCode) {
    this.invoiceCode = invoiceCode;
  }
	
  public String getInvoiceNo() {
  	return invoiceNo;
  }
	
  public void setInvoiceNo(String invoiceNo) {
    this.invoiceNo = invoiceNo;
  }
	
  public String getSellerTenantCode() {
  	return sellerTenantCode;
  }
	
  public void setSellerTenantCode(String sellerTenantCode) {
    this.sellerTenantCode = sellerTenantCode;
  }
	
  public String getSellerNo() {
  	return sellerNo;
  }
	
  public void setSellerNo(String sellerNo) {
    this.sellerNo = sellerNo;
  }
	
  public String getSellerNoFromPurchaser() {
  	return sellerNoFromPurchaser;
  }
	
  public void setSellerNoFromPurchaser(String sellerNoFromPurchaser) {
    this.sellerNoFromPurchaser = sellerNoFromPurchaser;
  }
	
  public String getSellerCode() {
  	return sellerCode;
  }
	
  public void setSellerCode(String sellerCode) {
    this.sellerCode = sellerCode;
  }
	
  public String getSellerTaxNo() {
  	return sellerTaxNo;
  }
	
  public void setSellerTaxNo(String sellerTaxNo) {
    this.sellerTaxNo = sellerTaxNo;
  }
	
  public String getSellerName() {
  	return sellerName;
  }
	
  public void setSellerName(String sellerName) {
    this.sellerName = sellerName;
  }
	
  public String getSellerAddrTel() {
  	return sellerAddrTel;
  }
	
  public void setSellerAddrTel(String sellerAddrTel) {
    this.sellerAddrTel = sellerAddrTel;
  }
	
  public String getSellerAddress() {
  	return sellerAddress;
  }
	
  public void setSellerAddress(String sellerAddress) {
    this.sellerAddress = sellerAddress;
  }
	
  public String getSellerTel() {
  	return sellerTel;
  }
	
  public void setSellerTel(String sellerTel) {
    this.sellerTel = sellerTel;
  }
	
  public String getSellerBankInfo() {
  	return sellerBankInfo;
  }
	
  public void setSellerBankInfo(String sellerBankInfo) {
    this.sellerBankInfo = sellerBankInfo;
  }
	
  public String getSellerBankName() {
  	return sellerBankName;
  }
	
  public void setSellerBankName(String sellerBankName) {
    this.sellerBankName = sellerBankName;
  }
	
  public String getSellerBankAccount() {
  	return sellerBankAccount;
  }
	
  public void setSellerBankAccount(String sellerBankAccount) {
    this.sellerBankAccount = sellerBankAccount;
  }
	
  public String getPurchaserTenantCode() {
  	return purchaserTenantCode;
  }
	
  public void setPurchaserTenantCode(String purchaserTenantCode) {
    this.purchaserTenantCode = purchaserTenantCode;
  }
	
  public String getPurchaserNo() {
  	return purchaserNo;
  }
	
  public void setPurchaserNo(String purchaserNo) {
    this.purchaserNo = purchaserNo;
  }
	
  public String getPurchaserNoFromSeller() {
  	return purchaserNoFromSeller;
  }
	
  public void setPurchaserNoFromSeller(String purchaserNoFromSeller) {
    this.purchaserNoFromSeller = purchaserNoFromSeller;
  }
	
  public String getPurchaserCode() {
  	return purchaserCode;
  }
	
  public void setPurchaserCode(String purchaserCode) {
    this.purchaserCode = purchaserCode;
  }
	
  public String getPurchaserTaxNo() {
  	return purchaserTaxNo;
  }
	
  public void setPurchaserTaxNo(String purchaserTaxNo) {
    this.purchaserTaxNo = purchaserTaxNo;
  }
	
  public String getTaxPurchaserName() {
  	return taxPurchaserName;
  }
	
  public void setTaxPurchaserName(String taxPurchaserName) {
    this.taxPurchaserName = taxPurchaserName;
  }
	
  public String getPurchaserName() {
  	return purchaserName;
  }
	
  public void setPurchaserName(String purchaserName) {
    this.purchaserName = purchaserName;
  }
	
  public String getPurchaserAddrTel() {
  	return purchaserAddrTel;
  }
	
  public void setPurchaserAddrTel(String purchaserAddrTel) {
    this.purchaserAddrTel = purchaserAddrTel;
  }
	
  public String getPurchaserAddress() {
  	return purchaserAddress;
  }
	
  public void setPurchaserAddress(String purchaserAddress) {
    this.purchaserAddress = purchaserAddress;
  }
	
  public String getPurchaserTel() {
  	return purchaserTel;
  }
	
  public void setPurchaserTel(String purchaserTel) {
    this.purchaserTel = purchaserTel;
  }
	
  public String getPurchaserBankInfo() {
  	return purchaserBankInfo;
  }
	
  public void setPurchaserBankInfo(String purchaserBankInfo) {
    this.purchaserBankInfo = purchaserBankInfo;
  }
	
  public String getPurchaserBankName() {
  	return purchaserBankName;
  }
	
  public void setPurchaserBankName(String purchaserBankName) {
    this.purchaserBankName = purchaserBankName;
  }
	
  public String getPurchaserBankAccount() {
  	return purchaserBankAccount;
  }
	
  public void setPurchaserBankAccount(String purchaserBankAccount) {
    this.purchaserBankAccount = purchaserBankAccount;
  }
	
  public BigDecimal getTaxRate() {
  	return taxRate;
  }
	
  public void setTaxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
  }
	
  public BigDecimal getAmountWithoutTax() {
  	return amountWithoutTax;
  }
	
  public void setAmountWithoutTax(BigDecimal amountWithoutTax) {
    this.amountWithoutTax = amountWithoutTax;
  }
	
  public BigDecimal getTaxAmount() {
  	return taxAmount;
  }
	
  public void setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
  }
	
  public BigDecimal getAmountWithTax() {
  	return amountWithTax;
  }
	
  public void setAmountWithTax(BigDecimal amountWithTax) {
    this.amountWithTax = amountWithTax;
  }
	
  public String getPaperDrewDate() {
  	return paperDrewDate;
  }
	
  public void setPaperDrewDate(String paperDrewDate) {
    this.paperDrewDate = paperDrewDate;
  }
	
  public String getInvoiceOrig() {
  	return invoiceOrig;
  }
	
  public void setInvoiceOrig(String invoiceOrig) {
    this.invoiceOrig = invoiceOrig;
  }
	
  public String getTwoCodeFlag() {
  	return twoCodeFlag;
  }
	
  public void setTwoCodeFlag(String twoCodeFlag) {
    this.twoCodeFlag = twoCodeFlag;
  }
	
  public String getCipherTextTwoCode() {
  	return cipherTextTwoCode;
  }
	
  public void setCipherTextTwoCode(String cipherTextTwoCode) {
    this.cipherTextTwoCode = cipherTextTwoCode;
  }
	
  public String getCipherText() {
  	return cipherText;
  }
	
  public void setCipherText(String cipherText) {
    this.cipherText = cipherText;
  }
	
  public String getREMARK() {
  	return REMARK;
  }
	
  public void setREMARK(String REMARK) {
    this.REMARK = REMARK;
  }
	
  public String getCashierName() {
  	return cashierName;
  }
	
  public void setCashierName(String cashierName) {
    this.cashierName = cashierName;
  }
	
  public String getCheckerName() {
  	return checkerName;
  }
	
  public void setCheckerName(String checkerName) {
    this.checkerName = checkerName;
  }
	
  public String getInvoicerName() {
  	return invoicerName;
  }
	
  public void setInvoicerName(String invoicerName) {
    this.invoicerName = invoicerName;
  }
	
  public String getMachineCode() {
  	return machineCode;
  }
	
  public void setMachineCode(String machineCode) {
    this.machineCode = machineCode;
  }
	
  public String getScanTime() {
  	return scanTime;
  }
	
  public void setScanTime(String scanTime) {
    this.scanTime = scanTime;
  }
	
  public Integer getScanOrder() {
  	return scanOrder;
  }
	
  public void setScanOrder(Integer scanOrder) {
    this.scanOrder = scanOrder;
  }
	
  public String getScanUserId() {
  	return scanUserId;
  }
	
  public void setScanUserId(String scanUserId) {
    this.scanUserId = scanUserId;
  }
	
  public String getScanUserName() {
  	return scanUserName;
  }
	
  public void setScanUserName(String scanUserName) {
    this.scanUserName = scanUserName;
  }
	
  public String getScanBatchNo() {
  	return scanBatchNo;
  }
	
  public void setScanBatchNo(String scanBatchNo) {
    this.scanBatchNo = scanBatchNo;
  }
	
  public String getScanDeductionImageUrl() {
  	return scanDeductionImageUrl;
  }
	
  public void setScanDeductionImageUrl(String scanDeductionImageUrl) {
    this.scanDeductionImageUrl = scanDeductionImageUrl;
  }
	
  public String getScanInvoiceImageUrl() {
  	return scanInvoiceImageUrl;
  }
	
  public void setScanInvoiceImageUrl(String scanInvoiceImageUrl) {
    this.scanInvoiceImageUrl = scanInvoiceImageUrl;
  }
	
  public String getScanStatus() {
  	return scanStatus;
  }
	
  public void setScanStatus(String scanStatus) {
    this.scanStatus = scanStatus;
  }
	
  public Integer getScanNum() {
  	return scanNum;
  }
	
  public void setScanNum(Integer scanNum) {
    this.scanNum = scanNum;
  }
	
  public String getDrawoutTime() {
  	return drawoutTime;
  }
	
  public void setDrawoutTime(String drawoutTime) {
    this.drawoutTime = drawoutTime;
  }
	
  public String getDrawoutUserId() {
  	return drawoutUserId;
  }
	
  public void setDrawoutUserId(String drawoutUserId) {
    this.drawoutUserId = drawoutUserId;
  }
	
  public String getIsNeedAuth() {
  	return isNeedAuth;
  }
	
  public void setIsNeedAuth(String isNeedAuth) {
    this.isNeedAuth = isNeedAuth;
  }
	
  public String getLockFlag() {
  	return lockFlag;
  }
	
  public void setLockFlag(String lockFlag) {
    this.lockFlag = lockFlag;
  }
	
  public String getSTATUS() {
  	return STATUS;
  }
	
  public void setSTATUS(String STATUS) {
    this.STATUS = STATUS;
  }
	
  public String getOriginInvoiceNo() {
  	return originInvoiceNo;
  }
	
  public void setOriginInvoiceNo(String originInvoiceNo) {
    this.originInvoiceNo = originInvoiceNo;
  }
	
  public String getOriginInvoiceCode() {
  	return originInvoiceCode;
  }
	
  public void setOriginInvoiceCode(String originInvoiceCode) {
    this.originInvoiceCode = originInvoiceCode;
  }
	
  public String getRedNotificationNo() {
  	return redNotificationNo;
  }
	
  public void setRedNotificationNo(String redNotificationNo) {
    this.redNotificationNo = redNotificationNo;
  }
	
  public String getRedTime() {
  	return redTime;
  }
	
  public void setRedTime(String redTime) {
    this.redTime = redTime;
  }
	
  public String getRedFlag() {
  	return redFlag;
  }
	
  public void setRedFlag(String redFlag) {
    this.redFlag = redFlag;
  }
	
  public String getProcessFlag() {
  	return processFlag;
  }
	
  public void setProcessFlag(String processFlag) {
    this.processFlag = processFlag;
  }
	
  public String getProcessRemark() {
  	return processRemark;
  }
	
  public void setProcessRemark(String processRemark) {
    this.processRemark = processRemark;
  }
	
  public String getSystemOrig() {
  	return systemOrig;
  }
	
  public void setSystemOrig(String systemOrig) {
    this.systemOrig = systemOrig;
  }
	
  public String getCheckCode() {
  	return checkCode;
  }
	
  public void setCheckCode(String checkCode) {
    this.checkCode = checkCode;
  }
	
  public String getTpBatchNo() {
  	return tpBatchNo;
  }
	
  public void setTpBatchNo(String tpBatchNo) {
    this.tpBatchNo = tpBatchNo;
  }
	
  public String getTP() {
  	return TP;
  }
	
  public void setTP(String TP) {
    this.TP = TP;
  }
	
  public String getAuditStatus() {
  	return auditStatus;
  }
	
  public void setAuditStatus(String auditStatus) {
    this.auditStatus = auditStatus;
  }
	
  public String getElGetInfoFlag() {
  	return elGetInfoFlag;
  }
	
  public void setElGetInfoFlag(String elGetInfoFlag) {
    this.elGetInfoFlag = elGetInfoFlag;
  }
	
  public String getElFlag() {
  	return elFlag;
  }
	
  public void setElFlag(String elFlag) {
    this.elFlag = elFlag;
  }
	
  public String getElTime() {
  	return elTime;
  }
	
  public void setElTime(String elTime) {
    this.elTime = elTime;
  }
	
  public String getElUserId() {
  	return elUserId;
  }
	
  public void setElUserId(String elUserId) {
    this.elUserId = elUserId;
  }
	
  public String getElRequestTime() {
  	return elRequestTime;
  }
	
  public void setElRequestTime(String elRequestTime) {
    this.elRequestTime = elRequestTime;
  }
	
  public String getElRequestUserId() {
  	return elRequestUserId;
  }
	
  public void setElRequestUserId(String elRequestUserId) {
    this.elRequestUserId = elRequestUserId;
  }
	
  public String getElCheckTime() {
  	return elCheckTime;
  }
	
  public void setElCheckTime(String elCheckTime) {
    this.elCheckTime = elCheckTime;
  }
	
  public String getElTaxPeriod() {
  	return elTaxPeriod;
  }
	
  public void setElTaxPeriod(String elTaxPeriod) {
    this.elTaxPeriod = elTaxPeriod;
  }
	
  public String getElEnsureRequestTime() {
  	return elEnsureRequestTime;
  }
	
  public void setElEnsureRequestTime(String elEnsureRequestTime) {
    this.elEnsureRequestTime = elEnsureRequestTime;
  }
	
  public String getElEnsureRequestUserId() {
  	return elEnsureRequestUserId;
  }
	
  public void setElEnsureRequestUserId(String elEnsureRequestUserId) {
    this.elEnsureRequestUserId = elEnsureRequestUserId;
  }
	
  public String getElEnsureTime() {
  	return elEnsureTime;
  }
	
  public void setElEnsureTime(String elEnsureTime) {
    this.elEnsureTime = elEnsureTime;
  }
	
  public String getElEnsureRemark() {
  	return elEnsureRemark;
  }
	
  public void setElEnsureRemark(String elEnsureRemark) {
    this.elEnsureRemark = elEnsureRemark;
  }
	
  public String getCooperateFlag() {
  	return cooperateFlag;
  }
	
  public void setCooperateFlag(String cooperateFlag) {
    this.cooperateFlag = cooperateFlag;
  }
	
  public String getRetreatStatus() {
  	return retreatStatus;
  }
	
  public void setRetreatStatus(String retreatStatus) {
    this.retreatStatus = retreatStatus;
  }
	
  public String getRetreatRemark() {
  	return retreatRemark;
  }
	
  public void setRetreatRemark(String retreatRemark) {
    this.retreatRemark = retreatRemark;
  }
	
  public String getSellerViewImageFlag() {
  	return sellerViewImageFlag;
  }
	
  public void setSellerViewImageFlag(String sellerViewImageFlag) {
    this.sellerViewImageFlag = sellerViewImageFlag;
  }
	
  public String getExceptionFlag() {
  	return exceptionFlag;
  }
	
  public void setExceptionFlag(String exceptionFlag) {
    this.exceptionFlag = exceptionFlag;
  }
	
  public String getComparisonFlag() {
  	return comparisonFlag;
  }
	
  public void setComparisonFlag(String comparisonFlag) {
    this.comparisonFlag = comparisonFlag;
  }
	
  public String getAuthResult() {
  	return authResult;
  }
	
  public void setAuthResult(String authResult) {
    this.authResult = authResult;
  }
	
  public String getAuthTime() {
  	return authTime;
  }
	
  public void setAuthTime(String authTime) {
    this.authTime = authTime;
  }
	
  public String getAuthRemark() {
  	return authRemark;
  }
	
  public void setAuthRemark(String authRemark) {
    this.authRemark = authRemark;
  }
	
  public String getAuthRequestTime() {
  	return authRequestTime;
  }
	
  public void setAuthRequestTime(String authRequestTime) {
    this.authRequestTime = authRequestTime;
  }
	
  public String getAuthRequestUserId() {
  	return authRequestUserId;
  }
	
  public void setAuthRequestUserId(String authRequestUserId) {
    this.authRequestUserId = authRequestUserId;
  }
	
  public String getAuthRequestUserName() {
  	return authRequestUserName;
  }
	
  public void setAuthRequestUserName(String authRequestUserName) {
    this.authRequestUserName = authRequestUserName;
  }
	
  public String getAuthRoute() {
  	return authRoute;
  }
	
  public void setAuthRoute(String authRoute) {
    this.authRoute = authRoute;
  }
	
  public String getAuthStatus() {
  	return authStatus;
  }
	
  public void setAuthStatus(String authStatus) {
    this.authStatus = authStatus;
  }
	
  public String getTaxFlag() {
  	return taxFlag;
  }
	
  public void setTaxFlag(String taxFlag) {
    this.taxFlag = taxFlag;
  }
	
  public String getTaxRequestTime() {
  	return taxRequestTime;
  }
	
  public void setTaxRequestTime(String taxRequestTime) {
    this.taxRequestTime = taxRequestTime;
  }
	
  public String getServiceCode() {
  	return serviceCode;
  }
	
  public void setServiceCode(String serviceCode) {
    this.serviceCode = serviceCode;
  }
	
  public String getIsNeedAllInfo() {
  	return isNeedAllInfo;
  }
	
  public void setIsNeedAllInfo(String isNeedAllInfo) {
    this.isNeedAllInfo = isNeedAllInfo;
  }
	
  public String getPdfPath() {
  	return pdfPath;
  }
	
  public void setPdfPath(String pdfPath) {
    this.pdfPath = pdfPath;
  }
	
  public String getOpStatus() {
  	return opStatus;
  }
	
  public void setOpStatus(String opStatus) {
    this.opStatus = opStatus;
  }
	
  public String getCreateTime() {
  	return createTime;
  }
	
  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }
	
  public String getCreateUserId() {
  	return createUserId;
  }
	
  public void setCreateUserId(String createUserId) {
    this.createUserId = createUserId;
  }
	
  public String getUpdateTime() {
  	return updateTime;
  }
	
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }
	
  public String getUpdateUserId() {
  	return updateUserId;
  }
	
  public void setUpdateUserId(String updateUserId) {
    this.updateUserId = updateUserId;
  }
	
  public String getSettlementMatchStatus() {
  	return settlementMatchStatus;
  }
	
  public void setSettlementMatchStatus(String settlementMatchStatus) {
    this.settlementMatchStatus = settlementMatchStatus;
  }
	
  public String getLogisticsStatus() {
  	return logisticsStatus;
  }
	
  public void setLogisticsStatus(String logisticsStatus) {
    this.logisticsStatus = logisticsStatus;
  }
	
  public String getPrintContentFlag() {
  	return printContentFlag;
  }
	
  public void setPrintContentFlag(String printContentFlag) {
    this.printContentFlag = printContentFlag;
  }
	
  public String getDiffStatus() {
  	return diffStatus;
  }
	
  public void setDiffStatus(String diffStatus) {
    this.diffStatus = diffStatus;
  }
	
  public String getTaxBureauOpenType() {
  	return taxBureauOpenType;
  }
	
  public void setTaxBureauOpenType(String taxBureauOpenType) {
    this.taxBureauOpenType = taxBureauOpenType;
  }
	
  public String getCancelExcepitonFlag() {
  	return cancelExcepitonFlag;
  }
	
  public void setCancelExcepitonFlag(String cancelExcepitonFlag) {
    this.cancelExcepitonFlag = cancelExcepitonFlag;
  }
	
  public String getAuthExceptionReason() {
  	return authExceptionReason;
  }
	
  public void setAuthExceptionReason(String authExceptionReason) {
    this.authExceptionReason = authExceptionReason;
  }
	
  public String getSaleListFileFlag() {
  	return saleListFileFlag;
  }
	
  public void setSaleListFileFlag(String saleListFileFlag) {
    this.saleListFileFlag = saleListFileFlag;
  }
	
  public String getInvoiceItemOrig() {
  	return invoiceItemOrig;
  }
	
  public void setInvoiceItemOrig(String invoiceItemOrig) {
    this.invoiceItemOrig = invoiceItemOrig;
  }
	
  public String getTaxFlagRemark() {
  	return taxFlagRemark;
  }
	
  public void setTaxFlagRemark(String taxFlagRemark) {
    this.taxFlagRemark = taxFlagRemark;
  }
	
  public String getInvoiceTag() {
  	return invoiceTag;
  }
	
  public void setInvoiceTag(String invoiceTag) {
    this.invoiceTag = invoiceTag;
  }
	
  public String getInvoiceTradeType() {
  	return invoiceTradeType;
  }
	
  public void setInvoiceTradeType(String invoiceTradeType) {
    this.invoiceTradeType = invoiceTradeType;
  }
	
  public String getInboundorderMatchStatus() {
  	return inboundorderMatchStatus;
  }
	
  public void setInboundorderMatchStatus(String inboundorderMatchStatus) {
    this.inboundorderMatchStatus = inboundorderMatchStatus;
  }
	
  public BigDecimal getInboundorderMatchNum() {
  	return inboundorderMatchNum;
  }
	
  public void setInboundorderMatchNum(BigDecimal inboundorderMatchNum) {
    this.inboundorderMatchNum = inboundorderMatchNum;
  }
	
  public String getMatchFirst() {
  	return matchFirst;
  }
	
  public void setMatchFirst(String matchFirst) {
    this.matchFirst = matchFirst;
  }
	
  public String getMatchSecond() {
  	return matchSecond;
  }
	
  public void setMatchSecond(String matchSecond) {
    this.matchSecond = matchSecond;
  }
	
  public String getTpCertificateNo() {
  	return tpCertificateNo;
  }
	
  public void setTpCertificateNo(String tpCertificateNo) {
    this.tpCertificateNo = tpCertificateNo;
  }
	
  public String getTpCertificatePeriod() {
  	return tpCertificatePeriod;
  }
	
  public void setTpCertificatePeriod(String tpCertificatePeriod) {
    this.tpCertificatePeriod = tpCertificatePeriod;
  }
	
  public String getCustomizeRemark1() {
  	return customizeRemark1;
  }
	
  public void setCustomizeRemark1(String customizeRemark1) {
    this.customizeRemark1 = customizeRemark1;
  }
	
  public String getCustomizeRemark2() {
  	return customizeRemark2;
  }
	
  public void setCustomizeRemark2(String customizeRemark2) {
    this.customizeRemark2 = customizeRemark2;
  }
	
  public String getCustomizeRemark3() {
  	return customizeRemark3;
  }
	
  public void setCustomizeRemark3(String customizeRemark3) {
    this.customizeRemark3 = customizeRemark3;
  }
	
  public String getEXT1() {
  	return EXT1;
  }
	
  public void setEXT1(String EXT1) {
    this.EXT1 = EXT1;
  }
	
  public String getEXT2() {
  	return EXT2;
  }
	
  public void setEXT2(String EXT2) {
    this.EXT2 = EXT2;
  }
	
  public String getEXT3() {
  	return EXT3;
  }
	
  public void setEXT3(String EXT3) {
    this.EXT3 = EXT3;
  }
	
  public String getEXT4() {
  	return EXT4;
  }
	
  public void setEXT4(String EXT4) {
    this.EXT4 = EXT4;
  }
	
  public String getEXT5() {
  	return EXT5;
  }
	
  public void setEXT5(String EXT5) {
    this.EXT5 = EXT5;
  }
	
  public String getEXT6() {
  	return EXT6;
  }
	
  public void setEXT6(String EXT6) {
    this.EXT6 = EXT6;
  }
	
  public String getEXT7() {
  	return EXT7;
  }
	
  public void setEXT7(String EXT7) {
    this.EXT7 = EXT7;
  }
	
  public String getEXT8() {
  	return EXT8;
  }
	
  public void setEXT8(String EXT8) {
    this.EXT8 = EXT8;
  }
	
  public String getEXT9() {
  	return EXT9;
  }
	
  public void setEXT9(String EXT9) {
    this.EXT9 = EXT9;
  }
	
  public String getEXT10() {
  	return EXT10;
  }
	
  public void setEXT10(String EXT10) {
    this.EXT10 = EXT10;
  }
	
  public String getShortTaxcodeStatus() {
  	return shortTaxcodeStatus;
  }
	
  public void setShortTaxcodeStatus(String shortTaxcodeStatus) {
    this.shortTaxcodeStatus = shortTaxcodeStatus;
  }
	
  public BigDecimal getEffectiveTaxAmount() {
  	return effectiveTaxAmount;
  }
	
  public void setEffectiveTaxAmount(BigDecimal effectiveTaxAmount) {
    this.effectiveTaxAmount = effectiveTaxAmount;
  }
	
  public String getUseRoute() {
  	return useRoute;
  }
	
  public void setUseRoute(String useRoute) {
    this.useRoute = useRoute;
  }

  @Override
  public String toString() {
    return "TPurchaserInvoice{" +
            "invoiceId='" + invoiceId + '\'' +
            ", preInvoiceId='" + preInvoiceId + '\'' +
            ", settlementId='" + settlementId + '\'' +
            ", settlementNo='" + settlementNo + '\'' +
            ", originSettlementNo='" + originSettlementNo + '\'' +
            ", sellerInvoiceId='" + sellerInvoiceId + '\'' +
            ", taxInvoiceId=" + taxInvoiceId +
            ", scanInvoiceId=" + scanInvoiceId +
            ", sellerInfoStatus='" + sellerInfoStatus + '\'' +
            ", taxInfoStatus='" + taxInfoStatus + '\'' +
            ", scanInfoStatus='" + scanInfoStatus + '\'' +
            ", invoiceType='" + invoiceType + '\'' +
            ", invoiceCode='" + invoiceCode + '\'' +
            ", invoiceNo='" + invoiceNo + '\'' +
            ", sellerTenantCode='" + sellerTenantCode + '\'' +
            ", sellerNo='" + sellerNo + '\'' +
            ", sellerNoFromPurchaser='" + sellerNoFromPurchaser + '\'' +
            ", sellerCode='" + sellerCode + '\'' +
            ", sellerTaxNo='" + sellerTaxNo + '\'' +
            ", sellerName='" + sellerName + '\'' +
            ", sellerAddrTel='" + sellerAddrTel + '\'' +
            ", sellerAddress='" + sellerAddress + '\'' +
            ", sellerTel='" + sellerTel + '\'' +
            ", sellerBankInfo='" + sellerBankInfo + '\'' +
            ", sellerBankName='" + sellerBankName + '\'' +
            ", sellerBankAccount='" + sellerBankAccount + '\'' +
            ", purchaserTenantCode='" + purchaserTenantCode + '\'' +
            ", purchaserNo='" + purchaserNo + '\'' +
            ", purchaserNoFromSeller='" + purchaserNoFromSeller + '\'' +
            ", purchaserCode='" + purchaserCode + '\'' +
            ", purchaserTaxNo='" + purchaserTaxNo + '\'' +
            ", taxPurchaserName='" + taxPurchaserName + '\'' +
            ", purchaserName='" + purchaserName + '\'' +
            ", purchaserAddrTel='" + purchaserAddrTel + '\'' +
            ", purchaserAddress='" + purchaserAddress + '\'' +
            ", purchaserTel='" + purchaserTel + '\'' +
            ", purchaserBankInfo='" + purchaserBankInfo + '\'' +
            ", purchaserBankName='" + purchaserBankName + '\'' +
            ", purchaserBankAccount='" + purchaserBankAccount + '\'' +
            ", taxRate=" + taxRate +
            ", amountWithoutTax=" + amountWithoutTax +
            ", taxAmount=" + taxAmount +
            ", amountWithTax=" + amountWithTax +
            ", paperDrewDate='" + paperDrewDate + '\'' +
            ", invoiceOrig='" + invoiceOrig + '\'' +
            ", twoCodeFlag='" + twoCodeFlag + '\'' +
            ", cipherTextTwoCode='" + cipherTextTwoCode + '\'' +
            ", cipherText='" + cipherText + '\'' +
            ", REMARK='" + REMARK + '\'' +
            ", cashierName='" + cashierName + '\'' +
            ", checkerName='" + checkerName + '\'' +
            ", invoicerName='" + invoicerName + '\'' +
            ", machineCode='" + machineCode + '\'' +
            ", scanTime='" + scanTime + '\'' +
            ", scanOrder=" + scanOrder +
            ", scanUserId='" + scanUserId + '\'' +
            ", scanUserName='" + scanUserName + '\'' +
            ", scanBatchNo='" + scanBatchNo + '\'' +
            ", scanDeductionImageUrl='" + scanDeductionImageUrl + '\'' +
            ", scanInvoiceImageUrl='" + scanInvoiceImageUrl + '\'' +
            ", scanStatus='" + scanStatus + '\'' +
            ", scanNum=" + scanNum +
            ", drawoutTime='" + drawoutTime + '\'' +
            ", drawoutUserId='" + drawoutUserId + '\'' +
            ", isNeedAuth='" + isNeedAuth + '\'' +
            ", lockFlag='" + lockFlag + '\'' +
            ", STATUS='" + STATUS + '\'' +
            ", originInvoiceNo='" + originInvoiceNo + '\'' +
            ", originInvoiceCode='" + originInvoiceCode + '\'' +
            ", redNotificationNo='" + redNotificationNo + '\'' +
            ", redTime='" + redTime + '\'' +
            ", redFlag='" + redFlag + '\'' +
            ", processFlag='" + processFlag + '\'' +
            ", processRemark='" + processRemark + '\'' +
            ", systemOrig='" + systemOrig + '\'' +
            ", checkCode='" + checkCode + '\'' +
            ", tpBatchNo='" + tpBatchNo + '\'' +
            ", TP='" + TP + '\'' +
            ", auditStatus='" + auditStatus + '\'' +
            ", elGetInfoFlag='" + elGetInfoFlag + '\'' +
            ", elFlag='" + elFlag + '\'' +
            ", elTime='" + elTime + '\'' +
            ", elUserId='" + elUserId + '\'' +
            ", elRequestTime='" + elRequestTime + '\'' +
            ", elRequestUserId='" + elRequestUserId + '\'' +
            ", elCheckTime='" + elCheckTime + '\'' +
            ", elTaxPeriod='" + elTaxPeriod + '\'' +
            ", elEnsureRequestTime='" + elEnsureRequestTime + '\'' +
            ", elEnsureRequestUserId='" + elEnsureRequestUserId + '\'' +
            ", elEnsureTime='" + elEnsureTime + '\'' +
            ", elEnsureRemark='" + elEnsureRemark + '\'' +
            ", cooperateFlag='" + cooperateFlag + '\'' +
            ", retreatStatus='" + retreatStatus + '\'' +
            ", retreatRemark='" + retreatRemark + '\'' +
            ", sellerViewImageFlag='" + sellerViewImageFlag + '\'' +
            ", exceptionFlag='" + exceptionFlag + '\'' +
            ", comparisonFlag='" + comparisonFlag + '\'' +
            ", authResult='" + authResult + '\'' +
            ", authTime='" + authTime + '\'' +
            ", authRemark='" + authRemark + '\'' +
            ", authRequestTime='" + authRequestTime + '\'' +
            ", authRequestUserId='" + authRequestUserId + '\'' +
            ", authRequestUserName='" + authRequestUserName + '\'' +
            ", authRoute='" + authRoute + '\'' +
            ", authStatus='" + authStatus + '\'' +
            ", taxFlag='" + taxFlag + '\'' +
            ", taxRequestTime='" + taxRequestTime + '\'' +
            ", serviceCode='" + serviceCode + '\'' +
            ", isNeedAllInfo='" + isNeedAllInfo + '\'' +
            ", pdfPath='" + pdfPath + '\'' +
            ", opStatus='" + opStatus + '\'' +
            ", createTime='" + createTime + '\'' +
            ", createUserId='" + createUserId + '\'' +
            ", updateTime='" + updateTime + '\'' +
            ", updateUserId='" + updateUserId + '\'' +
            ", settlementMatchStatus='" + settlementMatchStatus + '\'' +
            ", logisticsStatus='" + logisticsStatus + '\'' +
            ", printContentFlag='" + printContentFlag + '\'' +
            ", diffStatus='" + diffStatus + '\'' +
            ", taxBureauOpenType='" + taxBureauOpenType + '\'' +
            ", cancelExcepitonFlag='" + cancelExcepitonFlag + '\'' +
            ", authExceptionReason='" + authExceptionReason + '\'' +
            ", saleListFileFlag='" + saleListFileFlag + '\'' +
            ", invoiceItemOrig='" + invoiceItemOrig + '\'' +
            ", taxFlagRemark='" + taxFlagRemark + '\'' +
            ", invoiceTag='" + invoiceTag + '\'' +
            ", invoiceTradeType='" + invoiceTradeType + '\'' +
            ", inboundorderMatchStatus='" + inboundorderMatchStatus + '\'' +
            ", inboundorderMatchNum=" + inboundorderMatchNum +
            ", matchFirst='" + matchFirst + '\'' +
            ", matchSecond='" + matchSecond + '\'' +
            ", tpCertificateNo='" + tpCertificateNo + '\'' +
            ", tpCertificatePeriod='" + tpCertificatePeriod + '\'' +
            ", customizeRemark1='" + customizeRemark1 + '\'' +
            ", customizeRemark2='" + customizeRemark2 + '\'' +
            ", customizeRemark3='" + customizeRemark3 + '\'' +
            ", EXT1='" + EXT1 + '\'' +
            ", EXT2='" + EXT2 + '\'' +
            ", EXT3='" + EXT3 + '\'' +
            ", EXT4='" + EXT4 + '\'' +
            ", EXT5='" + EXT5 + '\'' +
            ", EXT6='" + EXT6 + '\'' +
            ", EXT7='" + EXT7 + '\'' +
            ", EXT8='" + EXT8 + '\'' +
            ", EXT9='" + EXT9 + '\'' +
            ", EXT10='" + EXT10 + '\'' +
            ", shortTaxcodeStatus='" + shortTaxcodeStatus + '\'' +
            ", effectiveTaxAmount=" + effectiveTaxAmount +
            ", useRoute='" + useRoute + '\'' +
            '}';
  }
}
