package cn.victorplus.vehicle.mapper;

import cn.victorplus.vehicle.bean.db.Che300Brand;
import org.apache.ibatis.annotations.Param;

import java.util.Collection;
import java.util.List;

/**
warning
This file is generated by CodeMonkey
Please DO NOT modify this file
**/
public interface Che300BrandMapper extends BaseMapper<Che300Brand> {

	/**
	 * 根据品牌关键字获取实体列表
	 * @param name			品牌名称关键字
	 * @param firstLetter	品牌首字母
	 * @return
	 */
	public List<Che300Brand> getAll(@Param("name") String name, @Param("firstLetter") String firstLetter);

	/**
	 * <p>单个添加品牌，忽略已存在的
	 * @author : Zhao Yun
	 * @since : 2018/04/10 14:01
	 */
	void addIgnoreCarBrand(Che300Brand che300Brand);

	/**
	 * <p>批量添加品牌，忽略已存在的
	 * @author : Zhao Yun
	 * @since : 2018/04/10 14:01
	 */
	void addIgnoreCarBrands(@Param("collect") Collection<Che300Brand> collect);

	int countBrand(Long brandId);

	/**
	 * <p>批量添加品牌，忽略已存在的
	 * @author : Zhao Yun
	 * @since : 2018/04/10 14:01
	 */
	void getByChe300BrandId(Long brandId);

	void deletePositiveId();

}