package cn.victorplus.vehicle.mapper;

import cn.victorplus.vehicle.bean.db.Che300Year;
import org.apache.ibatis.annotations.Param;

import java.util.Collection;
import java.util.List;

/**
warning
This file is generated by CodeMonkey
Please DO NOT modify this file
**/
public interface Che300YearMapper extends BaseMapper<Che300Year> {

	/**
	 * 根据车系ID获取实体列表
	 * @param seriesId
	 * @return
	 */
	public List<Che300Year> getBySid(@Param("seriesId") Long seriesId);

	/**
	 * 根据车系ID 年代 获取记录数
	 * @param seriesId
	 * @return
	 */
	public List<Che300Year> getBySYid(@Param("seriesId") Long seriesId, @Param("yearName") String yearName);


	/**
	 * 根据车系ID获取实体列表
	 * @param seriesId
	 * @return
	 */
	public Che300Year getOneBySid(@Param("seriesId") Long seriesId);

	/**
	 * <p>单个添加年代款，忽略已存在的</p>
	 * @author : Zhao Yun
	 * @since : 2018/04/10 14:01
	 */
	void addIgnoreCarYear(Che300Year che300Year);

	/**
	 * <p>批量添加年代款，忽略已存在的</p>
	 * @author : Zhao Yun
	 * @since : 2018/04/10 14:01
	 */
	void addIgnoreCarYears(@Param("collect") Collection<Che300Year> collect);

}