package cn.victorplus.vehicle.mapper;

import cn.victorplus.vehicle.bean.db.Che300Series;
import org.apache.ibatis.annotations.Param;

import java.util.Collection;
import java.util.List;

/**
warning
This file is generated by CodeMonkey
Please DO NOT modify this file
**/
public interface Che300SeriesMapper extends BaseMapper<Che300Series> {

	/**
	 * 根据品牌ID获取实体列表
	 * @param brandId
	 * @return
	 */
	public List<Che300Series> getByBid(@Param("brandId") Long brandId);

	List<Che300Series> getByName(@Param("name") String name);

	Che300Series getBySeriesId(@Param("seriesId") String seriesId);

	List<Che300Series> getByBidAndFid(@Param("brandId") Long brandId, @Param("factoryId") Long factoryId);

	/**
	 * <p>单个添加车系，忽略已存在的</p>
	 * @author : Zhao Yun
	 * @since : 2018/04/10 14:01
	 */
	void addIgnoreCarSeries(Che300Series che300Series);


	int countSeries(Long seriesId);

	/**
	 * <p>批量添加车系，忽略已存在的</p>
	 * @author : Zhao Yun
	 * @since : 2018/04/10 14:01
	 */
	void addIgnoreCarSeriess(@Param("collect") Collection<Che300Series> collect);

	void deletePositiveId();

}